module.exports = {
  isPlayerOneName: '-',
  isPlayerOneId: '',
  isPlayerOneElo:'-',
  isPlayerOneStreak:'-',
  isPlayerOneLevel:'',
  isPlayerOneMatches:'-',
  isPlayerOneWinRate:'-',
  isPlayerOneAVGKD:'-',
  isPlayerOneWins:'-',
  isPlayerOneAvatar:'',
  isPlayerTwoWins:'-',
  isPlayerTwoName: '-',
  isPlayerTwoId: '',
  isPlayerTwoElo:'-',
  isPlayerTwoStreak:'-',
  isPlayerTwoLevel:'',
  isPlayerTwoMatches:'-',
  isPlayerTwoWinRate:'-',
  isPlayerTwoAVGKD:'-',
  isPlayerTwoAvatar:'',
  isPlayerTwoSteamLink:'',
  isPlayerOneSteamLink:''
}