module.exports = {
  isPlayerOneName: 'Player One',
  isPlayerOneId: '',
  isPlayerOneElo:'-',
  isPlayerOneWinStreak:'-',
  isPlayerOneLevel:'',
  isPlayerOneMatches:'-',
  isPlayerOneWinRate:'-',
  isPlayerOneAVGKD:'-',
  isPlayerOneWins:'-',
  isPlayerOneAvatar:'',
  isPlayerTwoWins:'-',
  isPlayerTwoName: 'Player Two',
  isPlayerTwoId: '',
  isPlayerTwoElo:'-',
  isPlayerTwoWinStreak:'-',
  isPlayerTwoLevel:'',
  isPlayerTwoMatches:'-',
  isPlayerTwoWinRate:'-',
  isPlayerTwoAVGKD:'-',
  isPlayerTwoAvatar:'',
  isPlayerTwoSteamLink:'',
  isPlayerOneSteamLink:'',
  isPlayerOneParams:'',
  isPlayerTwoParams:'',
  isPlayerOneCountry:'',
  isPlayerTwoCountry:'',
  isUserSession:'',
  isPreviousPush:'',
  isRecentSearches:'',
  isLoading:false,
}