module.exports = {
  isPlayerOneName: '-',
  isPlayerOneId: '',
  isPlayerOneElo:'-',
  isPlayerOneWinStreak:'-',
  isPlayerOneLevel:'',
  isPlayerOneMatches:'-',
  isPlayerOneWinRate:'-',
  isPlayerOneAVGKD:'-',
  isPlayerOneWins:'-',
  isPlayerOneAvatar:'',
  isPlayerTwoWins:'-',
  isPlayerTwoName: '-',
  isPlayerTwoId: '',
  isPlayerTwoElo:'-',
  isPlayerTwoWinStreak:'-',
  isPlayerTwoLevel:'',
  isPlayerTwoMatches:'-',
  isPlayerTwoWinRate:'-',
  isPlayerTwoAVGKD:'-',
  isPlayerTwoAvatar:'',
  isPlayerTwoSteamLink:'',
  isPlayerOneSteamLink:'',
  isPlayerOneParams:'',
  isPlayerTwoParams:'',
  isPlayerOneCountry:'',
  isPlayerTwoCountry:'',
  isUserSession:'',
  isUserMatches:'',
}